### ISSUE TITLE
not working on android 

### ISSUE THREAD

**Issue by Nadimkhan120** [alantoa/react-native-reanimated-player#5]
hi, player controls are not working on android.

import React from "react";
import Navigators from "./src/navigators";
import Store from "./src/Store";
import { Provider } from "react-redux";
import {
  initialWindowMetrics,
  SafeAreaProvider,
} from "react-native-safe-area-context";
import VideoPlayer from "react-native-reanimated-player";
import { useSharedValue } from "react-native-reanimated";

export default () => {
  const videoHeight = useSharedValue(300);
  const isFullScreen = useSharedValue(false);

  return (
    <SafeAreaProvider initialMetrics={initialWindowMetrics}>
      <VideoPlayer
        showOnStart={true}
        source={{
          uri: "https://famee.bitwork.tech/public/uploads/BkHyttGZb9.mp4",
        }}
        headerTitle={"Title in full screen mode"}
        onTapBack={() => {
          // Alert.alert('onTapBack');
        }}
        onTapMore={() => {
          // Alert.alert('onTapMore');
        }}
        onPausedChange={(state) => {
          //Alert.alert(`onPausedChange: ${state}`);
          //setPaused(state);
        }}
        videoHeight={videoHeight}
        //paused={paused}
        isFullScreen={isFullScreen}
        disableControl={false}
      />
    </SafeAreaProvider>
  );
};

at start controls shows but after playing video, they disapears

**Comment by alantoa** [comment]
@Nadimkhan120 Hi,
I just tested on android, It's no problem.
What's your `react-native-reanimated` & `react-native-gesture-handler` versions?

**Comment by Nadimkhan120** [comment]
react-native-reanimated is 2.3.1 and  react-native-gesture-handler is 2.3.0

**Comment by alantoa** [comment]
It's ok, could you show the video or gif? 
Let's me see the problem

**Comment by ashish-garg-25** [comment]
Hi, I am facing same issue please take a look
https://github.com/alantoa/react-native-reanimated-player/issues/9

**Comment by Arise-cn** [comment]
same questiopn
