### ISSUE TITLE
Unable to resolve module lottie-react-native ？

### ISSUE THREAD

**Issue by Bruce-Ming** [alantoa/react-native-reanimated-player#6]
Does it depend on lottie-react-native? I don't have lottie-react-native installed and I'm getting errors. Your documentation dependencies do not indicate that lottie-react-native is required

f you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | /* eslint-disable no-undef */
> 2 | import LottieView from 'lottie-react-native';
    |                         ^

**Comment by alantoa** [comment]
Yeah, my documentation is missing, `lottie-react-native` is required.
